server:
  port: 9010

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yunjiaoyang/abba-microservices
          search-paths: config-repo
  security:
    user:
      password: abba.123


